language: ruby
rvm:
  - 2.2
addons:
  code_climate:
    repo_token:
      secure: "AI1T+2M7C2XLLx+7/8j5ZJQzWHlEy3aa934usmwFXAX2V8iPJJT3yOIevl/Nr1pPKNVi9WBZXwv3QVcFhBgsPQJoC5vvzMDfERLrKThV4qkZ2DxcihKEAguBE4ySORHDmAF4KpQ7WXWym23y7pCI+pghGBl/psd3KjK3bzPMy8OALVTnVS8ECUfI6FDt6wAPhmTPQU0biDXcSjr4UQVh9UkEW+kH6FurIRvQowPWZ0Be1ZX9pE3AeLvu6Tu0RxRbgv2YV8STh6Ej56VfYTe+FezBsseLXYJ9PBDVNWCgdEMrK16PQGxpkzYLV6r4shdEYRZSUKgDtpKVNkylPaTc2iLu6ljWk3KvS03i8Z97DLp349tR2YD4sYO/4O+a/Yb5EVx0PG7gkvqK0zWkj9de0gTsn3NYajkkeksCp6X1wv3WKi5l8huWOKQDKDt5A6wMxacGoAGZmQEpYJFrJdqFURwWHDlnQ30Shv2zJALP2Jbv59Q8AIqGba1a53ef72RR6e5oTLDuKjRnmIhxBP8qyNa4+aU6D7iGdkyzOE0loiV4YD2F/U16J+NepbF34Yb78o/hJrGMGKPsnuLS0wQEtRT+F3jKP5/o095bxoISLjCh92ttncOqVzQRqLk8HpoCmoHTSvpYSu25+6Byef9wV/BClcIAoNZHzIhCS98Gduk="
